using Microsoft.EntityFrameworkCore.Migrations;

namespace ChildrenGift.Migrations
{
    public partial class InitialCreate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Children",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    FirstName = table.Column<string>(nullable: true),
                    LastName = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Children", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Gifts",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(nullable: true),
                    ChildId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Gifts", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Gifts_Children_ChildId",
                        column: x => x.ChildId,
                        principalTable: "Children",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Children",
                columns: new[] { "Id", "FirstName", "LastName" },
                values: new object[,]
                {
                    { 1, "Eda", "Crooks" },
                    { 73, "Pascale", "Mayert" },
                    { 72, "Serenity", "Stracke" },
                    { 71, "Theo", "Collier" },
                    { 70, "Stefanie", "Dickens" },
                    { 69, "Toney", "Cruickshank" },
                    { 68, "Bertrand", "Jacobi" },
                    { 67, "Ofelia", "Haag" },
                    { 66, "Gwen", "Flatley" },
                    { 65, "Albin", "Hoppe" },
                    { 64, "Esteban", "Cremin" },
                    { 63, "Annamarie", "Glover" },
                    { 62, "Barney", "Ledner" },
                    { 61, "Rachel", "Rolfson" },
                    { 60, "Gino", "Lang" },
                    { 59, "Katelynn", "Weissnat" },
                    { 58, "Ubaldo", "DuBuque" },
                    { 57, "Rudolph", "Shields" },
                    { 56, "Alysha", "Jones" },
                    { 55, "Emmalee", "Heller" },
                    { 54, "Coralie", "Nolan" },
                    { 53, "Eloy", "Abbott" },
                    { 74, "Anjali", "Prosacco" },
                    { 52, "Alene", "Schiller" },
                    { 75, "Ernestina", "Lemke" },
                    { 77, "Erwin", "Champlin" },
                    { 98, "Angus", "Hoppe" },
                    { 97, "Helen", "Parker" },
                    { 96, "Oren", "Wunsch" },
                    { 95, "Ron", "Swaniawski" },
                    { 94, "Tracy", "Fadel" },
                    { 93, "Jaunita", "Runte" },
                    { 92, "Elwin", "Hilll" },
                    { 91, "Woodrow", "Ward" },
                    { 90, "Desiree", "Dooley" },
                    { 89, "Drew", "Lakin" },
                    { 88, "Marisa", "Johnston" },
                    { 87, "Jaylon", "Kertzmann" },
                    { 86, "Salvador", "West" },
                    { 85, "Griffin", "Stark" },
                    { 84, "Genoveva", "Koepp" },
                    { 83, "Verdie", "Runolfsson" },
                    { 82, "Vivien", "Herzog" },
                    { 81, "Jaylan", "Torphy" },
                    { 80, "Marlen", "Leuschke" },
                    { 79, "Fleta", "Howe" },
                    { 78, "Alysson", "Blanda" },
                    { 76, "Diamond", "Grady" },
                    { 51, "Maribel", "O'Reilly" },
                    { 50, "Murl", "Gulgowski" },
                    { 49, "Major", "Deckow" },
                    { 22, "Karianne", "Conroy" },
                    { 21, "Mollie", "Hagenes" },
                    { 20, "Dagmar", "Botsford" },
                    { 19, "Kaci", "Harvey" },
                    { 18, "Mireya", "Vandervort" },
                    { 17, "Claudia", "Morar" },
                    { 16, "Delfina", "Kunze" },
                    { 15, "Quinn", "Gottlieb" },
                    { 14, "Rodrick", "Heaney" },
                    { 13, "Susan", "Runolfsdottir" },
                    { 12, "Sonny", "Mohr" },
                    { 11, "Makenna", "Denesik" },
                    { 10, "Harvey", "Wunsch" },
                    { 9, "Juliet", "Robel" },
                    { 8, "Hailie", "Gaylord" },
                    { 7, "Alfonso", "Hoeger" },
                    { 6, "Darrick", "Littel" },
                    { 5, "Jessy", "Ledner" },
                    { 4, "Quincy", "Schmidt" },
                    { 3, "Ian", "Quitzon" },
                    { 2, "Wava", "Weimann" },
                    { 23, "Esther", "Larkin" },
                    { 24, "Jerome", "Crona" },
                    { 25, "Kelsie", "Reinger" },
                    { 26, "Lucy", "Collins" },
                    { 48, "Osvaldo", "Heller" },
                    { 47, "Elvie", "Weimann" },
                    { 46, "Oswaldo", "Feest" },
                    { 45, "Hans", "Rice" },
                    { 44, "Forrest", "Robel" },
                    { 43, "Clair", "Maggio" },
                    { 42, "Eleanore", "Conn" },
                    { 41, "Clemens", "Hilpert" },
                    { 40, "Leif", "Hegmann" },
                    { 39, "Stanford", "O'Reilly" },
                    { 99, "Alessia", "Blanda" },
                    { 38, "Keanu", "Padberg" },
                    { 36, "Elroy", "Douglas" },
                    { 35, "Michele", "Ortiz" },
                    { 34, "Jayda", "Koelpin" },
                    { 33, "Leopold", "Kuhic" },
                    { 32, "Alfreda", "Koss" },
                    { 31, "Summer", "Krajcik" },
                    { 30, "Arne", "Romaguera" },
                    { 29, "America", "Welch" },
                    { 28, "Mina", "Abshire" },
                    { 27, "Leon", "Johnston" },
                    { 37, "Micaela", "Mayer" },
                    { 100, "Margot", "Mueller" }
                });

            migrationBuilder.InsertData(
                table: "Gifts",
                columns: new[] { "Id", "ChildId", "Name" },
                values: new object[,]
                {
                    { 80, 1, "alias" },
                    { 182, 58, "alias" },
                    { 228, 58, "alias" },
                    { 69, 59, "alias" },
                    { 213, 59, "alias" },
                    { 220, 59, "alias" },
                    { 9, 60, "alias" },
                    { 45, 60, "alias" },
                    { 56, 60, "alias" },
                    { 135, 60, "alias" },
                    { 206, 60, "alias" },
                    { 53, 61, "alias" },
                    { 141, 61, "alias" },
                    { 116, 62, "alias" },
                    { 171, 62, "alias" },
                    { 226, 62, "alias" },
                    { 165, 64, "alias" },
                    { 185, 64, "alias" },
                    { 139, 65, "alias" },
                    { 176, 66, "alias" },
                    { 114, 67, "alias" },
                    { 149, 67, "alias" },
                    { 224, 67, "alias" },
                    { 242, 67, "alias" },
                    { 59, 68, "alias" },
                    { 219, 68, "alias" },
                    { 92, 69, "alias" },
                    { 68, 70, "alias" },
                    { 2, 58, "alias" },
                    { 70, 70, "alias" },
                    { 200, 57, "alias" },
                    { 229, 56, "alias" },
                    { 42, 45, "alias" },
                    { 215, 45, "alias" },
                    { 248, 45, "alias" },
                    { 100, 46, "alias" },
                    { 183, 46, "alias" },
                    { 20, 48, "alias" },
                    { 95, 48, "alias" },
                    { 153, 48, "alias" },
                    { 201, 48, "alias" },
                    { 249, 48, "alias" },
                    { 130, 49, "alias" },
                    { 24, 50, "alias" },
                    { 40, 50, "alias" },
                    { 98, 50, "alias" },
                    { 11, 51, "alias" },
                    { 173, 51, "alias" },
                    { 4, 52, "alias" },
                    { 168, 52, "alias" },
                    { 34, 53, "alias" },
                    { 125, 53, "alias" },
                    { 214, 53, "alias" },
                    { 63, 54, "alias" },
                    { 102, 54, "alias" },
                    { 26, 55, "alias" },
                    { 74, 55, "alias" },
                    { 175, 56, "alias" },
                    { 191, 56, "alias" },
                    { 37, 57, "alias" },
                    { 71, 70, "alias" },
                    { 208, 70, "alias" },
                    { 232, 70, "alias" },
                    { 46, 84, "alias" },
                    { 234, 84, "alias" },
                    { 132, 85, "alias" },
                    { 151, 85, "alias" },
                    { 150, 86, "alias" },
                    { 58, 87, "alias" },
                    { 12, 88, "alias" },
                    { 154, 88, "alias" },
                    { 96, 89, "alias" },
                    { 79, 90, "alias" },
                    { 73, 91, "alias" },
                    { 86, 91, "alias" },
                    { 97, 91, "alias" },
                    { 144, 92, "alias" },
                    { 244, 92, "alias" },
                    { 194, 93, "alias" },
                    { 112, 94, "alias" },
                    { 231, 94, "alias" },
                    { 239, 95, "alias" },
                    { 113, 96, "alias" },
                    { 145, 96, "alias" },
                    { 5, 97, "alias" },
                    { 193, 97, "alias" },
                    { 245, 97, "alias" },
                    { 48, 98, "alias" },
                    { 127, 98, "alias" },
                    { 163, 99, "alias" },
                    { 25, 84, "alias" },
                    { 17, 83, "alias" },
                    { 159, 82, "alias" },
                    { 109, 82, "alias" },
                    { 76, 71, "alias" },
                    { 142, 71, "alias" },
                    { 197, 71, "alias" },
                    { 105, 72, "alias" },
                    { 160, 72, "alias" },
                    { 217, 72, "alias" },
                    { 147, 73, "alias" },
                    { 1, 74, "alias" },
                    { 152, 75, "alias" },
                    { 167, 75, "alias" },
                    { 246, 75, "alias" },
                    { 38, 76, "alias" },
                    { 87, 76, "alias" },
                    { 33, 45, "alias" },
                    { 136, 76, "alias" },
                    { 250, 77, "alias" },
                    { 174, 78, "alias" },
                    { 177, 78, "alias" },
                    { 218, 78, "alias" },
                    { 94, 79, "alias" },
                    { 138, 79, "alias" },
                    { 29, 80, "alias" },
                    { 131, 80, "alias" },
                    { 212, 80, "alias" },
                    { 225, 80, "alias" },
                    { 241, 80, "alias" },
                    { 35, 81, "alias" },
                    { 235, 81, "alias" },
                    { 43, 77, "alias" },
                    { 216, 44, "alias" },
                    { 134, 44, "alias" },
                    { 110, 44, "alias" },
                    { 44, 14, "alias" },
                    { 66, 14, "alias" },
                    { 18, 15, "alias" },
                    { 83, 15, "alias" },
                    { 238, 15, "alias" },
                    { 55, 16, "alias" },
                    { 118, 16, "alias" },
                    { 21, 17, "alias" },
                    { 120, 17, "alias" },
                    { 223, 17, "alias" },
                    { 91, 18, "alias" },
                    { 162, 18, "alias" },
                    { 57, 20, "alias" },
                    { 62, 20, "alias" },
                    { 122, 20, "alias" },
                    { 133, 20, "alias" },
                    { 28, 21, "alias" },
                    { 54, 21, "alias" },
                    { 90, 21, "alias" },
                    { 156, 21, "alias" },
                    { 157, 21, "alias" },
                    { 184, 21, "alias" },
                    { 202, 21, "alias" },
                    { 10, 22, "alias" },
                    { 52, 22, "alias" },
                    { 195, 22, "alias" },
                    { 13, 23, "alias" },
                    { 22, 14, "alias" },
                    { 230, 13, "alias" },
                    { 128, 13, "alias" },
                    { 115, 13, "alias" },
                    { 106, 1, "alias" },
                    { 126, 1, "alias" },
                    { 137, 1, "alias" },
                    { 158, 1, "alias" },
                    { 61, 2, "alias" },
                    { 161, 2, "alias" },
                    { 221, 2, "alias" },
                    { 119, 3, "alias" },
                    { 240, 4, "alias" },
                    { 19, 5, "alias" },
                    { 117, 5, "alias" },
                    { 186, 5, "alias" },
                    { 49, 6, "alias" },
                    { 39, 23, "alias" },
                    { 99, 6, "alias" },
                    { 129, 7, "alias" },
                    { 236, 7, "alias" },
                    { 15, 8, "alias" },
                    { 72, 8, "alias" },
                    { 169, 8, "alias" },
                    { 51, 9, "alias" },
                    { 65, 9, "alias" },
                    { 93, 9, "alias" },
                    { 198, 9, "alias" },
                    { 41, 10, "alias" },
                    { 155, 10, "alias" },
                    { 233, 12, "alias" },
                    { 31, 13, "alias" },
                    { 108, 6, "alias" },
                    { 192, 99, "alias" },
                    { 146, 23, "alias" },
                    { 88, 24, "alias" },
                    { 3, 38, "alias" },
                    { 23, 38, "alias" },
                    { 27, 38, "alias" },
                    { 32, 38, "alias" },
                    { 84, 38, "alias" },
                    { 6, 39, "alias" },
                    { 75, 39, "alias" },
                    { 82, 39, "alias" },
                    { 103, 39, "alias" },
                    { 124, 39, "alias" },
                    { 166, 39, "alias" },
                    { 7, 40, "alias" },
                    { 101, 40, "alias" },
                    { 178, 40, "alias" },
                    { 190, 40, "alias" },
                    { 14, 41, "alias" },
                    { 148, 41, "alias" },
                    { 247, 41, "alias" },
                    { 50, 42, "alias" },
                    { 143, 42, "alias" },
                    { 179, 42, "alias" },
                    { 211, 42, "alias" },
                    { 60, 43, "alias" },
                    { 196, 43, "alias" },
                    { 210, 43, "alias" },
                    { 222, 43, "alias" },
                    { 67, 44, "alias" },
                    { 187, 37, "alias" },
                    { 121, 37, "alias" },
                    { 89, 37, "alias" },
                    { 36, 37, "alias" },
                    { 140, 24, "alias" },
                    { 237, 24, "alias" },
                    { 78, 25, "alias" },
                    { 85, 25, "alias" },
                    { 111, 25, "alias" },
                    { 172, 25, "alias" },
                    { 205, 25, "alias" },
                    { 207, 25, "alias" },
                    { 16, 27, "alias" },
                    { 64, 27, "alias" },
                    { 181, 27, "alias" },
                    { 227, 28, "alias" },
                    { 199, 29, "alias" },
                    { 47, 24, "alias" },
                    { 107, 30, "alias" },
                    { 81, 31, "alias" },
                    { 204, 31, "alias" },
                    { 188, 32, "alias" },
                    { 209, 32, "alias" },
                    { 30, 33, "alias" },
                    { 123, 33, "alias" },
                    { 164, 33, "alias" },
                    { 8, 34, "alias" },
                    { 203, 34, "alias" },
                    { 104, 35, "alias" },
                    { 189, 35, "alias" },
                    { 77, 36, "alias" },
                    { 170, 36, "alias" },
                    { 180, 30, "alias" },
                    { 243, 99, "alias" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Gifts_ChildId",
                table: "Gifts",
                column: "ChildId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Gifts");

            migrationBuilder.DropTable(
                name: "Children");
        }
    }
}
