// <auto-generated />
using ChildrenGift.DatContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChildrenGift.Migrations
{
    [DbContext(typeof(ChildGiftContext))]
    [Migration("20230220185051_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChildrenGift.Models.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Eda",
                            LastName = "Crooks"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Wava",
                            LastName = "Weimann"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ian",
                            LastName = "Quitzon"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Quincy",
                            LastName = "Schmidt"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Jessy",
                            LastName = "Ledner"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Darrick",
                            LastName = "Littel"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Alfonso",
                            LastName = "Hoeger"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Hailie",
                            LastName = "Gaylord"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Juliet",
                            LastName = "Robel"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Harvey",
                            LastName = "Wunsch"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Makenna",
                            LastName = "Denesik"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Sonny",
                            LastName = "Mohr"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Susan",
                            LastName = "Runolfsdottir"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Rodrick",
                            LastName = "Heaney"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Quinn",
                            LastName = "Gottlieb"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Delfina",
                            LastName = "Kunze"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Claudia",
                            LastName = "Morar"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Mireya",
                            LastName = "Vandervort"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Kaci",
                            LastName = "Harvey"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Dagmar",
                            LastName = "Botsford"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Mollie",
                            LastName = "Hagenes"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Karianne",
                            LastName = "Conroy"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Esther",
                            LastName = "Larkin"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Jerome",
                            LastName = "Crona"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Kelsie",
                            LastName = "Reinger"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Lucy",
                            LastName = "Collins"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Leon",
                            LastName = "Johnston"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Mina",
                            LastName = "Abshire"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "America",
                            LastName = "Welch"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Arne",
                            LastName = "Romaguera"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Summer",
                            LastName = "Krajcik"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Alfreda",
                            LastName = "Koss"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Leopold",
                            LastName = "Kuhic"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Jayda",
                            LastName = "Koelpin"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Michele",
                            LastName = "Ortiz"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Elroy",
                            LastName = "Douglas"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Micaela",
                            LastName = "Mayer"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Keanu",
                            LastName = "Padberg"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Stanford",
                            LastName = "O'Reilly"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Leif",
                            LastName = "Hegmann"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Clemens",
                            LastName = "Hilpert"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Eleanore",
                            LastName = "Conn"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Clair",
                            LastName = "Maggio"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Forrest",
                            LastName = "Robel"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Hans",
                            LastName = "Rice"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Oswaldo",
                            LastName = "Feest"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Elvie",
                            LastName = "Weimann"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Osvaldo",
                            LastName = "Heller"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Major",
                            LastName = "Deckow"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Murl",
                            LastName = "Gulgowski"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Maribel",
                            LastName = "O'Reilly"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Alene",
                            LastName = "Schiller"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Eloy",
                            LastName = "Abbott"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Coralie",
                            LastName = "Nolan"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Emmalee",
                            LastName = "Heller"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Alysha",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Rudolph",
                            LastName = "Shields"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Ubaldo",
                            LastName = "DuBuque"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Katelynn",
                            LastName = "Weissnat"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Gino",
                            LastName = "Lang"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Rachel",
                            LastName = "Rolfson"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Barney",
                            LastName = "Ledner"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Annamarie",
                            LastName = "Glover"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Esteban",
                            LastName = "Cremin"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Albin",
                            LastName = "Hoppe"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Gwen",
                            LastName = "Flatley"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Ofelia",
                            LastName = "Haag"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Bertrand",
                            LastName = "Jacobi"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Toney",
                            LastName = "Cruickshank"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Stefanie",
                            LastName = "Dickens"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Theo",
                            LastName = "Collier"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Serenity",
                            LastName = "Stracke"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Pascale",
                            LastName = "Mayert"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Anjali",
                            LastName = "Prosacco"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Ernestina",
                            LastName = "Lemke"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Diamond",
                            LastName = "Grady"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Erwin",
                            LastName = "Champlin"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Alysson",
                            LastName = "Blanda"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Fleta",
                            LastName = "Howe"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Marlen",
                            LastName = "Leuschke"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Jaylan",
                            LastName = "Torphy"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Vivien",
                            LastName = "Herzog"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Verdie",
                            LastName = "Runolfsson"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Genoveva",
                            LastName = "Koepp"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Griffin",
                            LastName = "Stark"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Salvador",
                            LastName = "West"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Jaylon",
                            LastName = "Kertzmann"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Marisa",
                            LastName = "Johnston"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Drew",
                            LastName = "Lakin"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Desiree",
                            LastName = "Dooley"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Woodrow",
                            LastName = "Ward"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Elwin",
                            LastName = "Hilll"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Jaunita",
                            LastName = "Runte"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Tracy",
                            LastName = "Fadel"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Ron",
                            LastName = "Swaniawski"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Oren",
                            LastName = "Wunsch"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Helen",
                            LastName = "Parker"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Angus",
                            LastName = "Hoppe"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Alessia",
                            LastName = "Blanda"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Margot",
                            LastName = "Mueller"
                        });
                });

            modelBuilder.Entity("ChildrenGift.Models.Entities.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChildId")
                        .HasColumnName("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildId = 74,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 2,
                            ChildId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 3,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 4,
                            ChildId = 52,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 5,
                            ChildId = 97,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 6,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 7,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 8,
                            ChildId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 9,
                            ChildId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 10,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 11,
                            ChildId = 51,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 12,
                            ChildId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 13,
                            ChildId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 14,
                            ChildId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 15,
                            ChildId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 16,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 17,
                            ChildId = 83,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 18,
                            ChildId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 19,
                            ChildId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 20,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 21,
                            ChildId = 17,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 22,
                            ChildId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 23,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 24,
                            ChildId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 25,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 26,
                            ChildId = 55,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 27,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 28,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 29,
                            ChildId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 30,
                            ChildId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 31,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 32,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 33,
                            ChildId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 34,
                            ChildId = 53,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 35,
                            ChildId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 36,
                            ChildId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 37,
                            ChildId = 57,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 38,
                            ChildId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 39,
                            ChildId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 40,
                            ChildId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 41,
                            ChildId = 10,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 42,
                            ChildId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 43,
                            ChildId = 77,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 44,
                            ChildId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 45,
                            ChildId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 46,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 47,
                            ChildId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 48,
                            ChildId = 98,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 49,
                            ChildId = 6,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 50,
                            ChildId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 51,
                            ChildId = 9,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 52,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 53,
                            ChildId = 61,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 54,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 55,
                            ChildId = 16,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 56,
                            ChildId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 57,
                            ChildId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 58,
                            ChildId = 87,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 59,
                            ChildId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 60,
                            ChildId = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 61,
                            ChildId = 2,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 62,
                            ChildId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 63,
                            ChildId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 64,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 65,
                            ChildId = 9,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 66,
                            ChildId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 67,
                            ChildId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 68,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 69,
                            ChildId = 59,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 70,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 71,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 72,
                            ChildId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 73,
                            ChildId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 74,
                            ChildId = 55,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 75,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 76,
                            ChildId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 77,
                            ChildId = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 78,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 79,
                            ChildId = 90,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 80,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 81,
                            ChildId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 82,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 83,
                            ChildId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 84,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 85,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 86,
                            ChildId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 87,
                            ChildId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 88,
                            ChildId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 89,
                            ChildId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 90,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 91,
                            ChildId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 92,
                            ChildId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 93,
                            ChildId = 9,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 94,
                            ChildId = 79,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 95,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 96,
                            ChildId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 97,
                            ChildId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 98,
                            ChildId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 99,
                            ChildId = 6,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 100,
                            ChildId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 101,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 102,
                            ChildId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 103,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 104,
                            ChildId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 105,
                            ChildId = 72,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 106,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 107,
                            ChildId = 30,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 108,
                            ChildId = 6,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 109,
                            ChildId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 110,
                            ChildId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 111,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 112,
                            ChildId = 94,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 113,
                            ChildId = 96,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 114,
                            ChildId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 115,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 116,
                            ChildId = 62,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 117,
                            ChildId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 118,
                            ChildId = 16,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 119,
                            ChildId = 3,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 120,
                            ChildId = 17,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 121,
                            ChildId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 122,
                            ChildId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 123,
                            ChildId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 124,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 125,
                            ChildId = 53,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 126,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 127,
                            ChildId = 98,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 128,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 129,
                            ChildId = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 130,
                            ChildId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 131,
                            ChildId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 132,
                            ChildId = 85,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 133,
                            ChildId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 134,
                            ChildId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 135,
                            ChildId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 136,
                            ChildId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 137,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 138,
                            ChildId = 79,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 139,
                            ChildId = 65,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 140,
                            ChildId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 141,
                            ChildId = 61,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 142,
                            ChildId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 143,
                            ChildId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 144,
                            ChildId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 145,
                            ChildId = 96,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 146,
                            ChildId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 147,
                            ChildId = 73,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 148,
                            ChildId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 149,
                            ChildId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 150,
                            ChildId = 86,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 151,
                            ChildId = 85,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 152,
                            ChildId = 75,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 153,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 154,
                            ChildId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 155,
                            ChildId = 10,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 156,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 157,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 158,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 159,
                            ChildId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 160,
                            ChildId = 72,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 161,
                            ChildId = 2,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 162,
                            ChildId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 163,
                            ChildId = 99,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 164,
                            ChildId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 165,
                            ChildId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 166,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 167,
                            ChildId = 75,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 168,
                            ChildId = 52,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 169,
                            ChildId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 170,
                            ChildId = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 171,
                            ChildId = 62,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 172,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 173,
                            ChildId = 51,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 174,
                            ChildId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 175,
                            ChildId = 56,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 176,
                            ChildId = 66,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 177,
                            ChildId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 178,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 179,
                            ChildId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 180,
                            ChildId = 30,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 181,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 182,
                            ChildId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 183,
                            ChildId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 184,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 185,
                            ChildId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 186,
                            ChildId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 187,
                            ChildId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 188,
                            ChildId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 189,
                            ChildId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 190,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 191,
                            ChildId = 56,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 192,
                            ChildId = 99,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 193,
                            ChildId = 97,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 194,
                            ChildId = 93,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 195,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 196,
                            ChildId = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 197,
                            ChildId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 198,
                            ChildId = 9,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 199,
                            ChildId = 29,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 200,
                            ChildId = 57,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 201,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 202,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 203,
                            ChildId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 204,
                            ChildId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 205,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 206,
                            ChildId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 207,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 208,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 209,
                            ChildId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 210,
                            ChildId = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 211,
                            ChildId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 212,
                            ChildId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 213,
                            ChildId = 59,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 214,
                            ChildId = 53,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 215,
                            ChildId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 216,
                            ChildId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 217,
                            ChildId = 72,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 218,
                            ChildId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 219,
                            ChildId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 220,
                            ChildId = 59,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 221,
                            ChildId = 2,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 222,
                            ChildId = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 223,
                            ChildId = 17,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 224,
                            ChildId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 225,
                            ChildId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 226,
                            ChildId = 62,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 227,
                            ChildId = 28,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 228,
                            ChildId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 229,
                            ChildId = 56,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 230,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 231,
                            ChildId = 94,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 232,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 233,
                            ChildId = 12,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 234,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 235,
                            ChildId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 236,
                            ChildId = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 237,
                            ChildId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 238,
                            ChildId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 239,
                            ChildId = 95,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 240,
                            ChildId = 4,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 241,
                            ChildId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 242,
                            ChildId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 243,
                            ChildId = 99,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 244,
                            ChildId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 245,
                            ChildId = 97,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 246,
                            ChildId = 75,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 247,
                            ChildId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 248,
                            ChildId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 249,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 250,
                            ChildId = 77,
                            Name = "alias"
                        });
                });

            modelBuilder.Entity("ChildrenGift.Models.Entities.Gift", b =>
                {
                    b.HasOne("ChildrenGift.Models.Entities.Child", "Child")
                        .WithMany("Gifts")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
