// <auto-generated />
using ChildrenGift.DatContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChildrenGift.Migrations
{
    [DbContext(typeof(ChildGiftContext))]
    partial class ChildGiftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChildrenGift.Models.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Juvenal",
                            LastName = "Ferry"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Celestine",
                            LastName = "Dooley"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Broderick",
                            LastName = "Huels"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ronaldo",
                            LastName = "Grimes"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Astrid",
                            LastName = "Walsh"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Anibal",
                            LastName = "Hane"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Gaetano",
                            LastName = "Hills"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Milan",
                            LastName = "Yundt"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Domenica",
                            LastName = "Funk"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Leif",
                            LastName = "Kuphal"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Max",
                            LastName = "Leannon"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Stefanie",
                            LastName = "Connelly"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Clair",
                            LastName = "Hamill"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Kelsi",
                            LastName = "Orn"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Eleazar",
                            LastName = "Reilly"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Ahmad",
                            LastName = "Hodkiewicz"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Rodger",
                            LastName = "Mraz"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Krista",
                            LastName = "Heaney"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Kirsten",
                            LastName = "Runolfsdottir"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Adelle",
                            LastName = "Volkman"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Breana",
                            LastName = "Walsh"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Victor",
                            LastName = "Walker"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Makenzie",
                            LastName = "Dickens"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Sophie",
                            LastName = "Wunsch"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Devante",
                            LastName = "Reichel"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Jamil",
                            LastName = "Barton"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Isabel",
                            LastName = "Kilback"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Geraldine",
                            LastName = "Corkery"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Agustina",
                            LastName = "O'Kon"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Claud",
                            LastName = "Runolfsson"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Naomi",
                            LastName = "Mosciski"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Devan",
                            LastName = "Wilderman"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Bobbie",
                            LastName = "McKenzie"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Zakary",
                            LastName = "Effertz"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Dennis",
                            LastName = "Jaskolski"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Aniyah",
                            LastName = "Lesch"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Calista",
                            LastName = "Flatley"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Destiny",
                            LastName = "Jerde"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Lue",
                            LastName = "Walter"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Beau",
                            LastName = "Simonis"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Herminia",
                            LastName = "Wolf"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Tobin",
                            LastName = "Morar"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Anabel",
                            LastName = "Barton"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Torey",
                            LastName = "Shanahan"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Jacklyn",
                            LastName = "Legros"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Burnice",
                            LastName = "Kohler"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Martina",
                            LastName = "Satterfield"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Delaney",
                            LastName = "Dietrich"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Clementina",
                            LastName = "Casper"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Oren",
                            LastName = "Reichel"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Arely",
                            LastName = "Stoltenberg"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Ramiro",
                            LastName = "Wisoky"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Euna",
                            LastName = "Eichmann"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Larry",
                            LastName = "Deckow"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Orlando",
                            LastName = "Bins"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Otha",
                            LastName = "Wilderman"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Glen",
                            LastName = "Kirlin"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Maxie",
                            LastName = "Grady"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Nicolas",
                            LastName = "Jenkins"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Roberta",
                            LastName = "Howe"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Letha",
                            LastName = "Macejkovic"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Katelin",
                            LastName = "Hickle"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Tressie",
                            LastName = "Bailey"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Roselyn",
                            LastName = "Moen"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Lea",
                            LastName = "Bins"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Conner",
                            LastName = "Kessler"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Antonio",
                            LastName = "Durgan"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Rahsaan",
                            LastName = "Mitchell"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Linnea",
                            LastName = "Heller"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Kari",
                            LastName = "Casper"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Isabel",
                            LastName = "Trantow"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Lucie",
                            LastName = "Hahn"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Boyd",
                            LastName = "Schuster"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Frida",
                            LastName = "Robel"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Brenna",
                            LastName = "Halvorson"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Shaina",
                            LastName = "Goldner"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Liliane",
                            LastName = "Quigley"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Ila",
                            LastName = "Rowe"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Chance",
                            LastName = "Schmeler"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Mckenzie",
                            LastName = "Bechtelar"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Stone",
                            LastName = "Leuschke"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Keith",
                            LastName = "Prosacco"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Felicity",
                            LastName = "Larkin"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Modesta",
                            LastName = "Christiansen"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Jeffery",
                            LastName = "Block"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Cloyd",
                            LastName = "Schimmel"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Deven",
                            LastName = "Moen"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Selena",
                            LastName = "Larson"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Rosalinda",
                            LastName = "Walker"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Rosie",
                            LastName = "Baumbach"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Cristobal",
                            LastName = "Mann"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Jacey",
                            LastName = "Goyette"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Hellen",
                            LastName = "Goyette"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Clementine",
                            LastName = "Weber"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Gunnar",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Margarita",
                            LastName = "Hammes"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Marge",
                            LastName = "Hoppe"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Nikolas",
                            LastName = "Reichel"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Benton",
                            LastName = "Parker"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Leland",
                            LastName = "Watsica"
                        });
                });

            modelBuilder.Entity("ChildrenGift.Models.Entities.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 2,
                            ChildId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 3,
                            ChildId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 4,
                            ChildId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 5,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 6,
                            ChildId = 75,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 7,
                            ChildId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 8,
                            ChildId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 9,
                            ChildId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 10,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 11,
                            ChildId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 12,
                            ChildId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 13,
                            ChildId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 14,
                            ChildId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 15,
                            ChildId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 16,
                            ChildId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 17,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 18,
                            ChildId = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 19,
                            ChildId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 20,
                            ChildId = 96,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 21,
                            ChildId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 22,
                            ChildId = 52,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 23,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 24,
                            ChildId = 99,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 25,
                            ChildId = 65,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 26,
                            ChildId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 27,
                            ChildId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 28,
                            ChildId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 29,
                            ChildId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 30,
                            ChildId = 28,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 31,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 32,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 33,
                            ChildId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 34,
                            ChildId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 35,
                            ChildId = 77,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 36,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 37,
                            ChildId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 38,
                            ChildId = 4,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 39,
                            ChildId = 61,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 40,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 41,
                            ChildId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 42,
                            ChildId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 43,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 44,
                            ChildId = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 45,
                            ChildId = 94,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 46,
                            ChildId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 47,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 48,
                            ChildId = 6,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 49,
                            ChildId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 50,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 51,
                            ChildId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 52,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 53,
                            ChildId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 54,
                            ChildId = 87,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 55,
                            ChildId = 86,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 56,
                            ChildId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 57,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 58,
                            ChildId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 59,
                            ChildId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 60,
                            ChildId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 61,
                            ChildId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 62,
                            ChildId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 63,
                            ChildId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 64,
                            ChildId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 65,
                            ChildId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 66,
                            ChildId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 67,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 68,
                            ChildId = 75,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 69,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 70,
                            ChildId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 71,
                            ChildId = 55,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 72,
                            ChildId = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 73,
                            ChildId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 74,
                            ChildId = 74,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 75,
                            ChildId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 76,
                            ChildId = 59,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 77,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 78,
                            ChildId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 79,
                            ChildId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 80,
                            ChildId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 81,
                            ChildId = 56,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 82,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 83,
                            ChildId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 84,
                            ChildId = 65,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 85,
                            ChildId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 86,
                            ChildId = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 87,
                            ChildId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 88,
                            ChildId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 89,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 90,
                            ChildId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 91,
                            ChildId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 92,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 93,
                            ChildId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 94,
                            ChildId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 95,
                            ChildId = 9,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 96,
                            ChildId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 97,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 98,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 99,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 100,
                            ChildId = 74,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 101,
                            ChildId = 61,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 102,
                            ChildId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 103,
                            ChildId = 93,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 104,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 105,
                            ChildId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 106,
                            ChildId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 107,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 108,
                            ChildId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 109,
                            ChildId = 79,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 110,
                            ChildId = 28,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 111,
                            ChildId = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 112,
                            ChildId = 65,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 113,
                            ChildId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 114,
                            ChildId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 115,
                            ChildId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 116,
                            ChildId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 117,
                            ChildId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 118,
                            ChildId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 119,
                            ChildId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 120,
                            ChildId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 121,
                            ChildId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 122,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 123,
                            ChildId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 124,
                            ChildId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 125,
                            ChildId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 126,
                            ChildId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 127,
                            ChildId = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 128,
                            ChildId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 129,
                            ChildId = 65,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 130,
                            ChildId = 87,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 131,
                            ChildId = 74,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 132,
                            ChildId = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 133,
                            ChildId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 134,
                            ChildId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 135,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 136,
                            ChildId = 19,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 137,
                            ChildId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 138,
                            ChildId = 63,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 139,
                            ChildId = 93,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 140,
                            ChildId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 141,
                            ChildId = 4,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 142,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 143,
                            ChildId = 3,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 144,
                            ChildId = 99,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 145,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 146,
                            ChildId = 6,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 147,
                            ChildId = 28,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 148,
                            ChildId = 57,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 149,
                            ChildId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 150,
                            ChildId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 151,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 152,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 153,
                            ChildId = 66,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 154,
                            ChildId = 57,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 155,
                            ChildId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 156,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 157,
                            ChildId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 158,
                            ChildId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 159,
                            ChildId = 77,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 160,
                            ChildId = 56,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 161,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 162,
                            ChildId = 85,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 163,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 164,
                            ChildId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 165,
                            ChildId = 53,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 166,
                            ChildId = 63,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 167,
                            ChildId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 168,
                            ChildId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 169,
                            ChildId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 170,
                            ChildId = 95,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 171,
                            ChildId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 172,
                            ChildId = 17,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 173,
                            ChildId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 174,
                            ChildId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 175,
                            ChildId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 176,
                            ChildId = 94,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 177,
                            ChildId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 178,
                            ChildId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 179,
                            ChildId = 30,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 180,
                            ChildId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 181,
                            ChildId = 87,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 182,
                            ChildId = 90,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 183,
                            ChildId = 75,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 184,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 185,
                            ChildId = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 186,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 187,
                            ChildId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 188,
                            ChildId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 189,
                            ChildId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 190,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 191,
                            ChildId = 30,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 192,
                            ChildId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 193,
                            ChildId = 85,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 194,
                            ChildId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 195,
                            ChildId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 196,
                            ChildId = 19,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 197,
                            ChildId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 198,
                            ChildId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 199,
                            ChildId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 200,
                            ChildId = 74,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 201,
                            ChildId = 51,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 202,
                            ChildId = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 203,
                            ChildId = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 204,
                            ChildId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 205,
                            ChildId = 72,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 206,
                            ChildId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 207,
                            ChildId = 63,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 208,
                            ChildId = 3,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 209,
                            ChildId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 210,
                            ChildId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 211,
                            ChildId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 212,
                            ChildId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 213,
                            ChildId = 94,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 214,
                            ChildId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 215,
                            ChildId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 216,
                            ChildId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 217,
                            ChildId = 10,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 218,
                            ChildId = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 219,
                            ChildId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 220,
                            ChildId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 221,
                            ChildId = 86,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 222,
                            ChildId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 223,
                            ChildId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 224,
                            ChildId = 10,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 225,
                            ChildId = 66,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 226,
                            ChildId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 227,
                            ChildId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 228,
                            ChildId = 26,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 229,
                            ChildId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 230,
                            ChildId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 231,
                            ChildId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 232,
                            ChildId = 26,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 233,
                            ChildId = 4,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 234,
                            ChildId = 56,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 235,
                            ChildId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 236,
                            ChildId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 237,
                            ChildId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 238,
                            ChildId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 239,
                            ChildId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 240,
                            ChildId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 241,
                            ChildId = 85,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 242,
                            ChildId = 74,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 243,
                            ChildId = 61,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 244,
                            ChildId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 245,
                            ChildId = 16,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 246,
                            ChildId = 90,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 247,
                            ChildId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 248,
                            ChildId = 52,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 249,
                            ChildId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 250,
                            ChildId = 2,
                            Name = "alias"
                        });
                });

            modelBuilder.Entity("ChildrenGift.Models.Entities.Gift", b =>
                {
                    b.HasOne("ChildrenGift.Models.Entities.Child", "Child")
                        .WithMany("Gifts")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
