// <auto-generated />
using System;
using ChildrenGift.DatContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChildrenGift.Migrations
{
    [DbContext(typeof(ChildGiftContext))]
    partial class ChildGiftContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChildrenGift.Models.Entities.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Children");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Carrie",
                            LastName = "Schaefer"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Joelle",
                            LastName = "Pouros"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Mary",
                            LastName = "Schimmel"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Holly",
                            LastName = "Mohr"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Hannah",
                            LastName = "Koch"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Terrence",
                            LastName = "Ratke"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Elisha",
                            LastName = "Skiles"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Myriam",
                            LastName = "Conroy"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Esta",
                            LastName = "Watsica"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Asa",
                            LastName = "Fisher"
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Dallas",
                            LastName = "Morar"
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Ernest",
                            LastName = "Mosciski"
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Etha",
                            LastName = "Sipes"
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Daija",
                            LastName = "Schuppe"
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Ebba",
                            LastName = "Heidenreich"
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Walter",
                            LastName = "Walsh"
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Kaycee",
                            LastName = "Larson"
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Bertha",
                            LastName = "Konopelski"
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Gunner",
                            LastName = "Olson"
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Princess",
                            LastName = "Koepp"
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Terry",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Bryana",
                            LastName = "Cassin"
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Keyon",
                            LastName = "Kohler"
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Adella",
                            LastName = "Kihn"
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Patricia",
                            LastName = "Satterfield"
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Eugene",
                            LastName = "Lang"
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Maiya",
                            LastName = "Gleichner"
                        },
                        new
                        {
                            Id = 28,
                            FirstName = "Elisa",
                            LastName = "Leffler"
                        },
                        new
                        {
                            Id = 29,
                            FirstName = "Dolores",
                            LastName = "Mante"
                        },
                        new
                        {
                            Id = 30,
                            FirstName = "Ellsworth",
                            LastName = "Veum"
                        },
                        new
                        {
                            Id = 31,
                            FirstName = "Valentin",
                            LastName = "Beahan"
                        },
                        new
                        {
                            Id = 32,
                            FirstName = "Lillie",
                            LastName = "McDermott"
                        },
                        new
                        {
                            Id = 33,
                            FirstName = "Chadrick",
                            LastName = "Goldner"
                        },
                        new
                        {
                            Id = 34,
                            FirstName = "Mckenzie",
                            LastName = "Kuvalis"
                        },
                        new
                        {
                            Id = 35,
                            FirstName = "Bryon",
                            LastName = "Kshlerin"
                        },
                        new
                        {
                            Id = 36,
                            FirstName = "Jany",
                            LastName = "Morar"
                        },
                        new
                        {
                            Id = 37,
                            FirstName = "Alva",
                            LastName = "Zulauf"
                        },
                        new
                        {
                            Id = 38,
                            FirstName = "Chaz",
                            LastName = "Metz"
                        },
                        new
                        {
                            Id = 39,
                            FirstName = "Peter",
                            LastName = "Fahey"
                        },
                        new
                        {
                            Id = 40,
                            FirstName = "Randal",
                            LastName = "Bechtelar"
                        },
                        new
                        {
                            Id = 41,
                            FirstName = "Francis",
                            LastName = "Schmidt"
                        },
                        new
                        {
                            Id = 42,
                            FirstName = "Waino",
                            LastName = "Gorczany"
                        },
                        new
                        {
                            Id = 43,
                            FirstName = "Karina",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 44,
                            FirstName = "Norberto",
                            LastName = "O'Conner"
                        },
                        new
                        {
                            Id = 45,
                            FirstName = "Fidel",
                            LastName = "Pollich"
                        },
                        new
                        {
                            Id = 46,
                            FirstName = "Velda",
                            LastName = "Reichel"
                        },
                        new
                        {
                            Id = 47,
                            FirstName = "Noemy",
                            LastName = "Pfannerstill"
                        },
                        new
                        {
                            Id = 48,
                            FirstName = "Oren",
                            LastName = "Powlowski"
                        },
                        new
                        {
                            Id = 49,
                            FirstName = "Jaida",
                            LastName = "Bergnaum"
                        },
                        new
                        {
                            Id = 50,
                            FirstName = "Gregg",
                            LastName = "Cronin"
                        },
                        new
                        {
                            Id = 51,
                            FirstName = "Tremaine",
                            LastName = "Zemlak"
                        },
                        new
                        {
                            Id = 52,
                            FirstName = "Cortez",
                            LastName = "Johnston"
                        },
                        new
                        {
                            Id = 53,
                            FirstName = "Susana",
                            LastName = "Lueilwitz"
                        },
                        new
                        {
                            Id = 54,
                            FirstName = "Taylor",
                            LastName = "Morissette"
                        },
                        new
                        {
                            Id = 55,
                            FirstName = "Karson",
                            LastName = "Dickens"
                        },
                        new
                        {
                            Id = 56,
                            FirstName = "Lue",
                            LastName = "Schowalter"
                        },
                        new
                        {
                            Id = 57,
                            FirstName = "Maurice",
                            LastName = "Lindgren"
                        },
                        new
                        {
                            Id = 58,
                            FirstName = "Larue",
                            LastName = "Abernathy"
                        },
                        new
                        {
                            Id = 59,
                            FirstName = "Marcelina",
                            LastName = "Schiller"
                        },
                        new
                        {
                            Id = 60,
                            FirstName = "Bonita",
                            LastName = "Schuster"
                        },
                        new
                        {
                            Id = 61,
                            FirstName = "Carmen",
                            LastName = "Sauer"
                        },
                        new
                        {
                            Id = 62,
                            FirstName = "Adonis",
                            LastName = "Cartwright"
                        },
                        new
                        {
                            Id = 63,
                            FirstName = "Vivian",
                            LastName = "Sipes"
                        },
                        new
                        {
                            Id = 64,
                            FirstName = "Johathan",
                            LastName = "Fadel"
                        },
                        new
                        {
                            Id = 65,
                            FirstName = "Noe",
                            LastName = "Hyatt"
                        },
                        new
                        {
                            Id = 66,
                            FirstName = "Faustino",
                            LastName = "Macejkovic"
                        },
                        new
                        {
                            Id = 67,
                            FirstName = "Rowena",
                            LastName = "Towne"
                        },
                        new
                        {
                            Id = 68,
                            FirstName = "Beaulah",
                            LastName = "Mraz"
                        },
                        new
                        {
                            Id = 69,
                            FirstName = "Edwina",
                            LastName = "Lind"
                        },
                        new
                        {
                            Id = 70,
                            FirstName = "Alexzander",
                            LastName = "Mertz"
                        },
                        new
                        {
                            Id = 71,
                            FirstName = "Harrison",
                            LastName = "Bergnaum"
                        },
                        new
                        {
                            Id = 72,
                            FirstName = "Harley",
                            LastName = "Weissnat"
                        },
                        new
                        {
                            Id = 73,
                            FirstName = "Zackery",
                            LastName = "Lockman"
                        },
                        new
                        {
                            Id = 74,
                            FirstName = "Emil",
                            LastName = "Bernhard"
                        },
                        new
                        {
                            Id = 75,
                            FirstName = "Keon",
                            LastName = "Kuhic"
                        },
                        new
                        {
                            Id = 76,
                            FirstName = "Carson",
                            LastName = "Nitzsche"
                        },
                        new
                        {
                            Id = 77,
                            FirstName = "Madonna",
                            LastName = "Keeling"
                        },
                        new
                        {
                            Id = 78,
                            FirstName = "Napoleon",
                            LastName = "Marquardt"
                        },
                        new
                        {
                            Id = 79,
                            FirstName = "Adrain",
                            LastName = "Huel"
                        },
                        new
                        {
                            Id = 80,
                            FirstName = "Layne",
                            LastName = "Donnelly"
                        },
                        new
                        {
                            Id = 81,
                            FirstName = "Theodora",
                            LastName = "Hansen"
                        },
                        new
                        {
                            Id = 82,
                            FirstName = "Amira",
                            LastName = "O'Keefe"
                        },
                        new
                        {
                            Id = 83,
                            FirstName = "Laurence",
                            LastName = "Schoen"
                        },
                        new
                        {
                            Id = 84,
                            FirstName = "Adrienne",
                            LastName = "Haley"
                        },
                        new
                        {
                            Id = 85,
                            FirstName = "Kathlyn",
                            LastName = "Abernathy"
                        },
                        new
                        {
                            Id = 86,
                            FirstName = "Brad",
                            LastName = "Kerluke"
                        },
                        new
                        {
                            Id = 87,
                            FirstName = "Rita",
                            LastName = "Hammes"
                        },
                        new
                        {
                            Id = 88,
                            FirstName = "Merlin",
                            LastName = "Batz"
                        },
                        new
                        {
                            Id = 89,
                            FirstName = "Tate",
                            LastName = "Metz"
                        },
                        new
                        {
                            Id = 90,
                            FirstName = "Mckayla",
                            LastName = "Parisian"
                        },
                        new
                        {
                            Id = 91,
                            FirstName = "Marisol",
                            LastName = "Doyle"
                        },
                        new
                        {
                            Id = 92,
                            FirstName = "Adrian",
                            LastName = "Moen"
                        },
                        new
                        {
                            Id = 93,
                            FirstName = "Lucie",
                            LastName = "Bechtelar"
                        },
                        new
                        {
                            Id = 94,
                            FirstName = "Janae",
                            LastName = "Willms"
                        },
                        new
                        {
                            Id = 95,
                            FirstName = "Jillian",
                            LastName = "Simonis"
                        },
                        new
                        {
                            Id = 96,
                            FirstName = "Reyes",
                            LastName = "Bartell"
                        },
                        new
                        {
                            Id = 97,
                            FirstName = "Matteo",
                            LastName = "Brakus"
                        },
                        new
                        {
                            Id = 98,
                            FirstName = "Richie",
                            LastName = "Howell"
                        },
                        new
                        {
                            Id = 99,
                            FirstName = "Mittie",
                            LastName = "Purdy"
                        },
                        new
                        {
                            Id = 100,
                            FirstName = "Nils",
                            LastName = "Stark"
                        });
                });

            modelBuilder.Entity("ChildrenGift.Models.Entities.Gift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("GiftId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Gifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GiftId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 2,
                            GiftId = 12,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 3,
                            GiftId = 53,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 4,
                            GiftId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 5,
                            GiftId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 6,
                            GiftId = 62,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 7,
                            GiftId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 8,
                            GiftId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 9,
                            GiftId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 10,
                            GiftId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 11,
                            GiftId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 12,
                            GiftId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 13,
                            GiftId = 83,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 14,
                            GiftId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 15,
                            GiftId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 16,
                            GiftId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 17,
                            GiftId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 18,
                            GiftId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 19,
                            GiftId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 20,
                            GiftId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 21,
                            GiftId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 22,
                            GiftId = 6,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 23,
                            GiftId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 24,
                            GiftId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 25,
                            GiftId = 79,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 26,
                            GiftId = 72,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 27,
                            GiftId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 28,
                            GiftId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 29,
                            GiftId = 93,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 30,
                            GiftId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 31,
                            GiftId = 12,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 32,
                            GiftId = 59,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 33,
                            GiftId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 34,
                            GiftId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 35,
                            GiftId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 36,
                            GiftId = 63,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 37,
                            GiftId = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 38,
                            GiftId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 39,
                            GiftId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 40,
                            GiftId = 3,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 41,
                            GiftId = 73,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 42,
                            GiftId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 43,
                            GiftId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 44,
                            GiftId = 98,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 45,
                            GiftId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 46,
                            GiftId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 47,
                            GiftId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 48,
                            GiftId = 26,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 49,
                            GiftId = 3,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 50,
                            GiftId = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 51,
                            GiftId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 52,
                            GiftId = 29,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 53,
                            GiftId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 54,
                            GiftId = 29,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 55,
                            GiftId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 56,
                            GiftId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 57,
                            GiftId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 58,
                            GiftId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 59,
                            GiftId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 60,
                            GiftId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 61,
                            GiftId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 62,
                            GiftId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 63,
                            GiftId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 64,
                            GiftId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 65,
                            GiftId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 66,
                            GiftId = 95,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 67,
                            GiftId = 83,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 68,
                            GiftId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 69,
                            GiftId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 70,
                            GiftId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 71,
                            GiftId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 72,
                            GiftId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 73,
                            GiftId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 74,
                            GiftId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 75,
                            GiftId = 90,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 76,
                            GiftId = 19,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 77,
                            GiftId = 27,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 78,
                            GiftId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 79,
                            GiftId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 80,
                            GiftId = 44,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 81,
                            GiftId = 95,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 82,
                            GiftId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 83,
                            GiftId = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 84,
                            GiftId = 79,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 85,
                            GiftId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 86,
                            GiftId = 82,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 87,
                            GiftId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 88,
                            GiftId = 29,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 89,
                            GiftId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 90,
                            GiftId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 91,
                            GiftId = 75,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 92,
                            GiftId = 66,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 93,
                            GiftId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 94,
                            GiftId = 19,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 95,
                            GiftId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 96,
                            GiftId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 97,
                            GiftId = 38,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 98,
                            GiftId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 99,
                            GiftId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 100,
                            GiftId = 65,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 101,
                            GiftId = 52,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 102,
                            GiftId = 53,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 103,
                            GiftId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 104,
                            GiftId = 95,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 105,
                            GiftId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 106,
                            GiftId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 107,
                            GiftId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 108,
                            GiftId = 90,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 109,
                            GiftId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 110,
                            GiftId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 111,
                            GiftId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 112,
                            GiftId = 64,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 113,
                            GiftId = 46,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 114,
                            GiftId = 26,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 115,
                            GiftId = 96,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 116,
                            GiftId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 117,
                            GiftId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 118,
                            GiftId = 65,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 119,
                            GiftId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 120,
                            GiftId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 121,
                            GiftId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 122,
                            GiftId = 54,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 123,
                            GiftId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 124,
                            GiftId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 125,
                            GiftId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 126,
                            GiftId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 127,
                            GiftId = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 128,
                            GiftId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 129,
                            GiftId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 130,
                            GiftId = 59,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 131,
                            GiftId = 80,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 132,
                            GiftId = 17,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 133,
                            GiftId = 93,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 134,
                            GiftId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 135,
                            GiftId = 92,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 136,
                            GiftId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 137,
                            GiftId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 138,
                            GiftId = 29,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 139,
                            GiftId = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 140,
                            GiftId = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 141,
                            GiftId = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 142,
                            GiftId = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 143,
                            GiftId = 90,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 144,
                            GiftId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 145,
                            GiftId = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 146,
                            GiftId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 147,
                            GiftId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 148,
                            GiftId = 12,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 149,
                            GiftId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 150,
                            GiftId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 151,
                            GiftId = 15,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 152,
                            GiftId = 73,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 153,
                            GiftId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 154,
                            GiftId = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 155,
                            GiftId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 156,
                            GiftId = 97,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 157,
                            GiftId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 158,
                            GiftId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 159,
                            GiftId = 62,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 160,
                            GiftId = 17,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 161,
                            GiftId = 72,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 162,
                            GiftId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 163,
                            GiftId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 164,
                            GiftId = 79,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 165,
                            GiftId = 70,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 166,
                            GiftId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 167,
                            GiftId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 168,
                            GiftId = 87,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 169,
                            GiftId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 170,
                            GiftId = 55,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 171,
                            GiftId = 12,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 172,
                            GiftId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 173,
                            GiftId = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 174,
                            GiftId = 84,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 175,
                            GiftId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 176,
                            GiftId = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 177,
                            GiftId = 63,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 178,
                            GiftId = 90,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 179,
                            GiftId = 68,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 180,
                            GiftId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 181,
                            GiftId = 94,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 182,
                            GiftId = 1,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 183,
                            GiftId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 184,
                            GiftId = 41,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 185,
                            GiftId = 45,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 186,
                            GiftId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 187,
                            GiftId = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 188,
                            GiftId = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 189,
                            GiftId = 51,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 190,
                            GiftId = 94,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 191,
                            GiftId = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 192,
                            GiftId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 193,
                            GiftId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 194,
                            GiftId = 30,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 195,
                            GiftId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 196,
                            GiftId = 74,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 197,
                            GiftId = 98,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 198,
                            GiftId = 12,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 199,
                            GiftId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 200,
                            GiftId = 98,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 201,
                            GiftId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 202,
                            GiftId = 33,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 203,
                            GiftId = 78,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 204,
                            GiftId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 205,
                            GiftId = 88,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 206,
                            GiftId = 26,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 207,
                            GiftId = 56,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 208,
                            GiftId = 91,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 209,
                            GiftId = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 210,
                            GiftId = 97,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 211,
                            GiftId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 212,
                            GiftId = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 213,
                            GiftId = 76,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 214,
                            GiftId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 215,
                            GiftId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 216,
                            GiftId = 71,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 217,
                            GiftId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 218,
                            GiftId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 219,
                            GiftId = 35,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 220,
                            GiftId = 63,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 221,
                            GiftId = 93,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 222,
                            GiftId = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 223,
                            GiftId = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 224,
                            GiftId = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 225,
                            GiftId = 34,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 226,
                            GiftId = 77,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 227,
                            GiftId = 22,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 228,
                            GiftId = 87,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 229,
                            GiftId = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 230,
                            GiftId = 67,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 231,
                            GiftId = 12,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 232,
                            GiftId = 52,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 233,
                            GiftId = 20,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 234,
                            GiftId = 69,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 235,
                            GiftId = 83,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 236,
                            GiftId = 61,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 237,
                            GiftId = 23,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 238,
                            GiftId = 81,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 239,
                            GiftId = 52,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 240,
                            GiftId = 19,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 241,
                            GiftId = 51,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 242,
                            GiftId = 49,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 243,
                            GiftId = 42,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 244,
                            GiftId = 53,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 245,
                            GiftId = 60,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 246,
                            GiftId = 89,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 247,
                            GiftId = 58,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 248,
                            GiftId = 28,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 249,
                            GiftId = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 250,
                            GiftId = 7,
                            Name = "alias"
                        });
                });

            modelBuilder.Entity("ChildrenGift.Models.Entities.Gift", b =>
                {
                    b.HasOne("ChildrenGift.Models.Entities.Child", "Child")
                        .WithMany("Gifts")
                        .HasForeignKey("ChildId");
                });
#pragma warning restore 612, 618
        }
    }
}
